use std::env;
use std::ffi::OsStr;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

fn main() {
    let files: Vec<PathBuf> = env::args_os().skip(1).map(PathBuf::from).collect();

    if files.is_empty() {
        eprintln!("Usage: drag one or more files onto tobyte.exe");
        eprintln!("Or run: tobyte.exe <file> [file ...]");
        return;
    }

    let mut had_error = false;

    for input in files {
        match convert_file(&input) {
            Ok(output) => println!("wrote {}", output.display()),
            Err(error) => {
                had_error = true;
                eprintln!("{}: {}", input.display(), error);
            }
        }
    }

    if had_error {
        std::process::exit(1);
    }
}

fn convert_file(input: &Path) -> io::Result<PathBuf> {
    let metadata = fs::metadata(input)?;

    if !metadata.is_file() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "not a regular file",
        ));
    }

    let bytes = fs::read(input)?;
    let output = output_path(input);
    let variable = variable_name(input);
    let guard = header_guard(input);
    let original_name = input
        .file_name()
        .and_then(OsStr::to_str)
        .unwrap_or("file")
        .to_string();

    let header = render_header(&guard, &variable, &original_name, &bytes);
    fs::write(&output, header)?;

    Ok(output)
}

fn output_path(input: &Path) -> PathBuf {
    input.with_extension("h")
}

fn variable_name(input: &Path) -> String {
    let stem = input
        .file_stem()
        .and_then(OsStr::to_str)
        .filter(|name| !name.is_empty())
        .unwrap_or("file");

    let extension = input.extension().and_then(OsStr::to_str).unwrap_or("");
    let combined = if extension.is_empty() {
        stem.to_string()
    } else {
        format!("{stem}_{extension}")
    };

    let mut name = sanitize_identifier(&combined).to_ascii_lowercase();

    if name.is_empty() {
        name.push_str("file");
    }

    if name
        .as_bytes()
        .first()
        .is_some_and(|byte| byte.is_ascii_digit())
    {
        name.insert(0, '_');
    }

    name
}

fn header_guard(input: &Path) -> String {
    let file_name = input
        .file_name()
        .and_then(OsStr::to_str)
        .filter(|name| !name.is_empty())
        .unwrap_or("file");

    let mut guard = sanitize_identifier(file_name).to_ascii_uppercase();

    if guard.is_empty() {
        guard.push_str("FILE");
    }

    if guard
        .as_bytes()
        .first()
        .is_some_and(|byte| byte.is_ascii_digit())
    {
        guard.insert(0, '_');
    }

    format!("TOBYTE_{guard}_H")
}

fn sanitize_identifier(value: &str) -> String {
    let mut out = String::new();
    let mut last_was_underscore = false;

    for ch in value.chars() {
        let mapped = if ch.is_ascii_alphanumeric() { ch } else { '_' };

        if mapped == '_' {
            if !last_was_underscore {
                out.push(mapped);
            }
            last_was_underscore = true;
        } else {
            out.push(mapped);
            last_was_underscore = false;
        }
    }

    out.trim_matches('_').to_string()
}

fn render_header(guard: &str, variable: &str, original_name: &str, bytes: &[u8]) -> String {
    let mut out = String::new();

    out.push_str("/* Generated by tobyte. */\n");
    out.push_str("#ifndef ");
    out.push_str(guard);
    out.push('\n');
    out.push_str("#define ");
    out.push_str(guard);
    out.push_str("\n\n");

    out.push_str("static const unsigned char ");
    out.push_str(variable);
    out.push_str("[] = {");

    if !bytes.is_empty() {
        out.push('\n');

        for chunk in bytes.chunks(12) {
            out.push_str("    ");

            for (index, byte) in chunk.iter().enumerate() {
                if index > 0 {
                    out.push(' ');
                }
                out.push_str(&format!("0x{byte:02X},"));
            }

            out.push('\n');
        }
    }

    out.push_str("};\n\n");

    out.push_str("static const unsigned long long ");
    out.push_str(variable);
    out.push_str("_size = ");
    out.push_str(&bytes.len().to_string());
    out.push_str("ULL;\n");

    out.push_str("static const char ");
    out.push_str(variable);
    out.push_str("_name[] = \"");
    out.push_str(&escape_c_string(original_name));
    out.push_str("\";\n\n");

    out.push_str("#endif\n");

    out
}

fn escape_c_string(value: &str) -> String {
    let mut out = String::new();

    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            ch if ch.is_control() => out.push_str(&format!("\\x{:02X}", ch as u32)),
            ch => out.push(ch),
        }
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn variable_name_uses_stem_and_extension() {
        assert_eq!(variable_name(Path::new("My Image.png")), "my_image_png");
        assert_eq!(variable_name(Path::new("123.bin")), "_123_bin");
    }

    #[test]
    fn header_contains_bytes_size_and_name() {
        let header = render_header("TEST_H", "logo_png", "logo.png", &[0, 127, 255]);

        assert!(header.contains("static const unsigned char logo_png[]"));
        assert!(header.contains("0x00, 0x7F, 0xFF,"));
        assert!(header.contains("static const unsigned long long logo_png_size = 3ULL;"));
        assert!(header.contains("static const char logo_png_name[] = \"logo.png\";"));
    }
}
